[theme]
primaryColor = "#1b5897"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f4f9"
textColor = "#1a1a2e"
font = "sans serif"

[client]
toolbarMode = "viewer"

[server]
maxUploadSize = 50
